### ISSUE TITLE
Check for `type` uses `input` instead of `field`

### ISSUE THREAD

**Issue by davidhund** [cferdinandi/validate#19]
[validityState-polyfill.js:L19](https://github.com/cferdinandi/validate/blob/master/src/js/validityState-polyfill.js#L19) is currently:

```
var type = field.getAttribute('type') || input.nodeName.toLowerCase();
```

.. but should IMO be:

```
var type = field.getAttribute('type') || field.nodeName.toLowerCase();
```

**Comment by cferdinandi** [comment]
Yes!  Good catch! I'll get this fixed ASAP.

**Comment by cferdinandi** [comment]
Looks like I fixed this a while ago and never closed the issue.
