### ISSUE TITLE
Add Validation for ipv4 and ipv6 ip address ?

### ISSUE THREAD

**Issue by sivaprabug** [cferdinandi/validate#24]
Add Validation for ipv4 and ipv6 ip address ?

**Comment by cferdinandi** [comment]
No, sorry. This script augments native form validation attributes and properties.

You can add this yourself using a `pattern` attribute with a regex (and using a `title` for a custom error message).

Check on [my post on CSS Tricks](https://css-tricks.com/form-validation-part-1-constraint-validation-html/#article-header-id-2) for more info.
