### ISSUE TITLE
Cross Browser problems with checkboxes and radios.

### ISSUE THREAD

**Issue by iainhenderson** [cferdinandi/validate#31]
Hi, there seem to be some problems with checkboxes and radios on [your demo page](https://cferdinandi.github.io/validate/)  These impact different browsers in different ways.

**Chrome 61 Mac - Radio buttons**
Selecting 'Yes' is valid, selecting 'No' is invalid

**Safari 11 Mac - Radio buttons**
'Yes' and 'No' are both invalid

**Firefox 55. - Radio buttons**
'Yes' and 'No' are both invalid

**Chrome 61 - Checkboxes**
Only "Wolverine" is valid

**Safari 11 - Checkboxes**
No options are valid

**Firefox 55 - Checkboxes**
No options are valid

**Comment by cferdinandi** [comment]
Hmm... I'm seeing this too. I'll look into this, thanks!

**Comment by cferdinandi** [comment]
Sorry for the lengthy delay in fixing this. It appears to have been causing by a polyfill conflict, and should be resolved with v1.1.3.

Looks like it may have been caused by a conflict with this: https://github.com/cferdinandi/validate/issues/27
