### ISSUE TITLE
Should capturing be set to true when removing the blur handler?

### ISSUE THREAD

**Issue by murdoch** [cferdinandi/validate#34]
In `validate.init()` you attach a listener to the **blur** event, with capturing set to true, like so:

    document.addEventListener('blur', blurHandler, true);

But in `validate.destroy()` that same listener is removed with capturing set to false:

    document.removeEventListener('blur', blurHandler, false);

Should capturing be set to true when removing the listener, in order to be consistent? Pardon me if I'm wrong. Maybe it doesn't matter?

**Comment by cferdinandi** [comment]
This PR was supposed to fix this: https://github.com/cferdinandi/validate/pull/28

But, I'm looking and it didn't. Hmm... I'll issue a new PR for it. Thanks!

**Comment by cferdinandi** [comment]
Fixed with v1.1.1
