### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by shelldandy** [cferdinandi/validate#45]

**Comment by cferdinandi** [comment]
Sorry, this is an added burden on maintenance that I'm not interested in taking on at the moment. I know that sucks for certain dev processes, but I maintain dozens of OSS projects.

I know `npm publish` doesn't seem like a lot, but on top of updates, pushing, creating a PR, and merging, it's just one more step to mess up.

**Comment by shelldandy** [comment]
I understand and respect that haha i also maintain about a dozen OSS things and its a pain
