### ISSUE TITLE
Custom error for specific input types

### ISSUE THREAD

**Issue by entozoon** [cferdinandi/validate#48]
Hey there, firstly - love the package, it's wicked!

Not sure if a bug or feature request but I can't find a simple way to change the typical required error message for, say, a 'do you accept.. ' checkbox as "Please fill out this field." doesn't quite ring true.

Also, this should totally be a legit npm package. Installing it through github is.. fine.. but it breaks if you subsequently install another package - you have to delete node_modules and re-install it all (for reason that are beyond me).

**Comment by cferdinandi** [comment]
Really good point. I'll see what I can do here.

**Comment by cferdinandi** [comment]
I just added custom error messages for checkboxes and radio buttons: https://github.com/cferdinandi/validate#global-settings
