### ISSUE TITLE
Is there a option to use in CDN?

### ISSUE THREAD

**Issue by danilowoz** [cferdinandi/validate#49]

**Comment by cferdinandi** [comment]
Not at this time, though that is something I've considered. I'm leaving this open as a feature request. No target date to implement.

**Comment by cferdinandi** [comment]
Just pushed validate 2.0.0, that includes a combined file with the polyfills (as well as a standalone), and a CDN option.

https://github.com/cferdinandi/validate#1-include-validatejs-on-your-site
