### ISSUE TITLE
How do I change the error message?

### ISSUE THREAD

**Issue by paveell** [cferdinandi/validate#56]
Please tell me how to display an error message inside the `<span class="input__text"></span>` field, as shown in the example?

```
<span class="input__text">
	  <span class="input__label">Name</span>
	  Error message: <span id="error" class="input__error"></span>
</span>
```

Thank you
**Test case:** https://jsfiddle.net/cferdinandi/yhqepa3x/

**Comment by cferdinandi** [comment]
I'm unable to provide support for custom modifications to the core code like this right now. Sorry!
