### ISSUE TITLE
Radio issues in IE preventing submission

### ISSUE THREAD

**Issue by alexcarpenter** [cferdinandi/validate#60]
When working with required radios in IE, you always get an error. I've included the polyfill script as well. See attached gif and test case.

![radio-issues](https://user-images.githubusercontent.com/825855/44363892-8d259b80-a493-11e8-896f-dae59c4bfed6.gif)

**Test case:** https://codepen.io/alexcarpenter/pen/BOawNy

Browserstack test 
![image 2018-08-20 at 4 19 44 pm](https://user-images.githubusercontent.com/825855/44364437-ff4ab000-a494-11e8-817d-cac3b3a33234.png)

**Comment by cferdinandi** [comment]
Ok so... after lots of testing and trying to update/improve the polyfill, I decided to just give up. The native API is a total pain to work with.

I just created a new form validation plugin, [Bouncer](https://github.com/cferdinandi/bouncer), that's the same size as Validate.js *and* uses native form validation elements, but works a little differently under the hood. 

I'm deprecating Validate.js today.
