### ISSUE TITLE
Textarea error message

### ISSUE THREAD

**Issue by maciejcieslik** [cferdinandi/validate#61]
**Test case:** https://jsfiddle.net/yhqepa3x/1/

error message from textarea don't disappear when value is not empty anymore and error message is appended on every focus.

**Comment by fabs2011** [comment]
You have empty spaces in your name attributes. I understand that it isn't forbidden but do you really need to? If you add the "required" validation rule to "Numer telefonu" for example, the plugin fails as it does with the textarea (named "txt#Wiadomość"), it doesn't like that "#". 
Use camelCase or underscores in your html code if you can or even better use "id" and write whatever you like in the "name" attribute, even empty spaces and the plugin works like a charm! See [this](https://stackoverflow.com/questions/70579/what-are-valid-values-for-the-id-attribute-in-html/79022#79022 ) for more details if you interested.

**Comment by maciejcieslik** [comment]
Spaces are for cms, so it just take name and instert it in a mail to admin, but  i don't understand why validate names? Type should be validated and optionally a pattern. Validation shouldn't care about names as this can be sometimes really weird (in example on the backend name="lorem[ipsum][0]").

**Comment by cferdinandi** [comment]
This is a big irrespective of naming convention. The name can have spaces.

**Comment by cferdinandi** [comment]
The native API is a total pain to work with.

I just created a new form validation plugin, [Bouncer](https://github.com/cferdinandi/bouncer), that's the same size as Validate.js *and* uses native form validation elements, but works a little differently under the hood. 

I'm deprecating Validate.js today and replacing it with [Bouncer](https://github.com/cferdinandi/bouncer).
